### PR TITLE
Handle error code

### PR DESCRIPTION
**Pull request by asahasrabuddhe**

### CODE REVIEW

**Comment by asahasrabuddhe** [comment]
gometalinter has been deprecated. will have to make more changes

**Comment by AudriusButkevicius** [comment]
Added write rights, yet this still fails

**Comment by asahasrabuddhe** [comment]
this is failing due to dependency issue as i migrated the linter. I will have this pass :)

**Comment by asahasrabuddhe** [comment]
> Added write rights, yet this still fails

look at that! fixed :)

**Comment by asahasrabuddhe** [comment]
> Added write rights, yet this still fails
access

looks like i have only read access...

**Comment by AudriusButkevicius** [comment]
Fixed that

**Comment by asahasrabuddhe** [comment]
> Fixed that

Thanks a lot!

**Pull request merged**
